// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// em_fit_cpp
Rcpp::List em_fit_cpp(const arma::mat& X, const arma::uvec& subj, const arma::uvec& grid, const arma::uvec& panel, const arma::vec& dN, const arma::uvec& panelsubj, arma::uword n, arma::uword K, arma::vec beta, arma::vec lambda, arma::uword maxit, double reltol, bool accelerate);
RcppExport SEXP _pcdreg_em_fit_cpp(SEXP XSEXP, SEXP subjSEXP, SEXP gridSEXP, SEXP panelSEXP, SEXP dNSEXP, SEXP panelsubjSEXP, SEXP nSEXP, SEXP KSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP maxitSEXP, SEXP reltolSEXP, SEXP accelerateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type subj(subjSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type panel(panelSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dN(dNSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type panelsubj(panelsubjSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    Rcpp::traits::input_parameter< bool >::type accelerate(accelerateSEXP);
    rcpp_result_gen = Rcpp::wrap(em_fit_cpp(X, subj, grid, panel, dN, panelsubj, n, K, beta, lambda, maxit, reltol, accelerate));
    return rcpp_result_gen;
END_RCPP
}
// covariance_cpp
Rcpp::List covariance_cpp(const arma::mat& X, const arma::uvec& subj, const arma::uvec& grid, const arma::uvec& panel, const arma::vec& dN, const arma::uvec& panelsubj, arma::uword n, arma::uword K, const arma::vec& beta, const arma::vec& lambda);
RcppExport SEXP _pcdreg_covariance_cpp(SEXP XSEXP, SEXP subjSEXP, SEXP gridSEXP, SEXP panelSEXP, SEXP dNSEXP, SEXP panelsubjSEXP, SEXP nSEXP, SEXP KSEXP, SEXP betaSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type subj(subjSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type panel(panelSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dN(dNSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type panelsubj(panelsubjSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(covariance_cpp(X, subj, grid, panel, dN, panelsubj, n, K, beta, lambda));
    return rcpp_result_gen;
END_RCPP
}
// profile_gradient_cpp
Rcpp::List profile_gradient_cpp(const arma::mat& X, const arma::uvec& subj, const arma::uvec& grid, const arma::uvec& panel, const arma::vec& dN, const arma::uvec& panelsubj, arma::uword n, arma::uword K, const arma::vec& beta, const arma::vec& lambda, double h, arma::uword maxit, double reltol);
RcppExport SEXP _pcdreg_profile_gradient_cpp(SEXP XSEXP, SEXP subjSEXP, SEXP gridSEXP, SEXP panelSEXP, SEXP dNSEXP, SEXP panelsubjSEXP, SEXP nSEXP, SEXP KSEXP, SEXP betaSEXP, SEXP lambdaSEXP, SEXP hSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type subj(subjSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type panel(panelSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type dN(dNSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type panelsubj(panelsubjSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(profile_gradient_cpp(X, subj, grid, panel, dN, panelsubj, n, K, beta, lambda, h, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}
// mean_fit_cpp
Rcpp::List mean_fit_cpp(const arma::mat& X, const arma::uvec& subj, const arma::uvec& grid, const arma::vec& cN, arma::uword n, arma::uword K, arma::vec beta, arma::uword maxit, double reltol);
RcppExport SEXP _pcdreg_mean_fit_cpp(SEXP XSEXP, SEXP subjSEXP, SEXP gridSEXP, SEXP cNSEXP, SEXP nSEXP, SEXP KSEXP, SEXP betaSEXP, SEXP maxitSEXP, SEXP reltolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type subj(subjSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type cN(cNSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type K(KSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type reltol(reltolSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_fit_cpp(X, subj, grid, cN, n, K, beta, maxit, reltol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pcdreg_em_fit_cpp", (DL_FUNC) &_pcdreg_em_fit_cpp, 13},
    {"_pcdreg_covariance_cpp", (DL_FUNC) &_pcdreg_covariance_cpp, 10},
    {"_pcdreg_profile_gradient_cpp", (DL_FUNC) &_pcdreg_profile_gradient_cpp, 13},
    {"_pcdreg_mean_fit_cpp", (DL_FUNC) &_pcdreg_mean_fit_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_pcdreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
