# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_fit_cpp <- function(X, subj, grid, panel, dN, panelsubj, n, K, beta, lambda, maxit, reltol, accelerate) {
    .Call(`_pcdreg_em_fit_cpp`, X, subj, grid, panel, dN, panelsubj, n, K, beta, lambda, maxit, reltol, accelerate)
}

covariance_cpp <- function(X, subj, grid, panel, dN, panelsubj, n, K, beta, lambda) {
    .Call(`_pcdreg_covariance_cpp`, X, subj, grid, panel, dN, panelsubj, n, K, beta, lambda)
}

profile_gradient_cpp <- function(X, subj, grid, panel, dN, panelsubj, n, K, beta, lambda, h, maxit, reltol) {
    .Call(`_pcdreg_profile_gradient_cpp`, X, subj, grid, panel, dN, panelsubj, n, K, beta, lambda, h, maxit, reltol)
}

mean_fit_cpp <- function(X, subj, grid, cN, n, K, beta, maxit, reltol) {
    .Call(`_pcdreg_mean_fit_cpp`, X, subj, grid, cN, n, K, beta, maxit, reltol)
}

